### PR TITLE
Create gl2vec

### PR DESCRIPTION
**Pull request by jian8li**

### CODE REVIEW

**Comment by MaxwellRebo** [comment]
Please append new links to bottom of README. See current format. Thanks!

**Comment by jian8li** [comment]
Hi Maxwell,

Here is the link to the paper on arXiv..

https://arxiv.org/pdf/1812.05473.pdf

Can you kindly help us add gl2vec to the list?

Thank you very much for your help.

Best,
Jian

**Comment by MaxwellRebo** [comment]
Rather than add as a new file, please add to the **bottom** of README.md, using the format of the others. Redo the pull request when that is done. Thank you.

**Comment by jian8li** [comment]
Just do that.  Thank you for your guidance.

Best,
Jian

**Pull request merged**
